# Nombre del servicio para identificacion dentro del ecosistema.
spring.application.name=anpa-config-server

# Puerto donde se levantara el servidor.
server.port=8888

# URI del repositorio donde se almacenan los archivos de configuracion de las aplicaciones.
spring.cloud.config.server.git.uri=https://github.com/FedeOA/anpa-config-data
spring.cloud.config.server.git.default-label=release/1.0.0

# Configuracion para que el servidor de configuracion clone el repositorio al levantar.
# Esto asegura que el servidor tenga acceso a las configuraciones actualizadas desde el inicio.
spring.cloud.config.server.git.clone-on-start=true

# Nombre de usuario para autenticarse en el repositorio.
spring.cloud.config.server.git.username=FedeOA

# Token de acceso al repositorio anpa-config-data. Si es repo publico, no hace falta token.
spring.cloud.config.server.git.password=${ANPA_MICROSERVICES_GITHUB_TOKEN}